# This is the checkov workflow with actions
 
 
on: [push]
jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: wget the config file
        run:  mkdir config && wget -O config/checkov_config.yaml https://raw.githubusercontent.com/Lymer07/iac_checkov/master/config_checkov.yaml?token=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
      - name: print the
        run:  'ls -al'
      - name:  pull the docker
        run:  docker pull bridgecrew/checkov
      - name: mount the 2 volumes and run checkov
        run:  docker run --tty --volume $(pwd):/tf --workdir /tf bridgecrew/checkov --directory  https://raw.githubusercontent.com/Lymer07/iac_checkov/terraformcode  --config-file /tf/config/checkov_config.yaml --external-checks-git https://github.com/Lymer07/iac_checkov.git//custom_checks
        
